version: '3.9'

services:
  redis-db:
    hostname: redis-db
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

      
  pokemon-api:
    container_name: pokemon-api
    image: pokemon-api
    ports:
      - "8080:8080"
    networks:
      - backend
    links:
      - redis-db
    depends_on:
      - redis-db
      
networks:
  backend:
